name: Deploy static content to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel older runs so Pages never blocks on "in progress deployment"
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pnpm (per official guidance)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Node + cache for pnpm store
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build-time fetch:
      # - Scans wndgur2/BlogDB posts/**.md|mdx
      # - Scans ALL public repos under wndgur2, parses README frontmatter
      # Outputs to public/meta/* and public/posts/*
      - name: Generate static content (Octokit)
        env:
          # Prefer GH_PAT for higher rate limits/private repos (optional)
          GH_PAT: ${{ secrets.GH_PAT }}
          PROJECTS_OWNER: wndgur2
          BLOG_DB_REPO: wndgur2/BlogDB
          BLOG_DB_REF: main
          POSTS_DIR: posts
        run: pnpm exec node scripts/fetch-content.js

      - name: Build site
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
