name: Deploy static content to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate static content (Octokit)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}         # <-- add in repo settings
          BLOG_DB_REPO: wndgur2/BlogDB          # optional override
          BLOG_DB_REF: main                     # optional override
          POSTS_DIR: posts                      # optional override
          OWNER_FOR_PROJECTS: wndgur2           # optional override
          PROJECTS_META_PATH: meta/projects.json# optional override
        run: node scripts/fetch-content.js

      - name: Build site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
